const Images = {
  Laptop: () => require("./Laptop.png"),
  Logo: () => require("./Logo.png"),
  Rocket: () => require("./Rocket.png"),
  SadFace: () => require("./SadFace.png"),
  Successfull: () => require("./Successfull.png"),
  Add: () => require("./icons/Add.png"),
  AddSavings: () => require("./icons/Add2.png"),
  Google: () => require("./icons/Google.png"),
  HidePassword: () => require("./icons/HidePassword.png"),
  Home: () => require("./icons/Home.png"),
  LeftArrow: () => require("./icons/LeftArrow.png"),
  Letter: () => require("./icons/Letter.png"),
  Lock: () => require("./icons/Lock.png"),
  Notification: () => require("./icons/Notification.png"),
  Person: () => require("./icons/Person.png"),
  RightArrow: () => require("./icons/RightArrow.png"),
  Savings: () => require("./icons/Savings.png"),
  Reminder: () => require("./icons/reminder.png"),
  Wallet: () => require("./icons/Wallet.png"),
  Calendar: () => require("./icons/calendar.png"),
  Dollar: () => require("./icons/dollarIcon.png"),
  More: () => require("./icons/more.png"),
  Pencil: () => require("./icons/pencil.png"),
  HamburgerMenu: () => require("./icons/hamburgerMenu.png"),
  goal: () => require("./icons/goalIcon.png"),
  ShowPassword: () => require("./icons/visiblePassword.png"),
  menu: () => require("./icons/menu.png"),
  logout: () => require("./icons/logout.png"),
};

export default Images;
